# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [34]:
arr = np.array(my_list)
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,3,4],[1,4,5],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 3, 4],
       [1, 4, 5],
       [7, 8, 9]])

In [7]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [8]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.65092562, 0.02381806, 0.19616875, 0.74664219, 0.71882054])

In [13]:
np.random.randn(2,2)

array([[-0.05832121,  0.36850217],
       [ 0.19995304,  1.47473019]])

In [14]:
np.random.randint(9)

2

In [15]:
ranarr = np.random.randint(0,20,6)

In [16]:
ranarr

array([10, 12,  5, 12, 16,  5])

In [17]:
ranarr.max()

16

In [18]:
ranarr.min()

5

In [19]:
ranarr.argmin()

2

In [20]:
ranarr.dtype

dtype('int64')

In [21]:
from numpy.random import randint

In [22]:
randint(1,10)

3

In [23]:
# index slicing
arr = np.arange(1,11)

In [24]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[5]

6

In [26]:
arr[1:5]

array([2, 3, 4, 5])

In [27]:
arr_2d = np.array([[5,10,14],[20,23,4],[1,2,3]])

In [28]:
arr_2d

array([[ 5, 10, 14],
       [20, 23,  4],
       [ 1,  2,  3]])

In [29]:
arr_2d[2][2]

3

In [30]:
arr_2d[2,1]

2

In [31]:
arr_2d[:2,1:]

array([[10, 14],
       [23,  4]])

In [32]:
arr_2d[1:]

array([[20, 23,  4],
       [ 1,  2,  3]])

In [35]:
arr = np.arange(1,11)

In [ ]:
bool_arr = arr > 5

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>5]

In [ ]:
arr[arr<4]

In [ ]:
new_ar_2d = np.arange(50).reshape(5,10)
new_ar_2d

In [ ]:
new_ar_2d[1:3,2:5]

# Numpy operations

In [ ]:
myarr = np.arange(0,11)

In [ ]:
myarr

In [ ]:
myarr*2

In [ ]:
myarr + myarr

In [ ]:
myarr- myarr

In [ ]:
myarr / myarr

# Exercises

In [38]:
# learnpython.org exercise
weight_kg = [81.65,97.52,95.25,92.98, 86.18,88.45]
np_weight_kg = np.array(weight_kg)
np_weight_lbs = np_weight_kg * 2.2
print(np_weight_lbs)

[179.63  214.544 209.55  204.556 189.596 194.59 ]
