# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,3,4],[1,4,5],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 3, 4],
       [1, 4, 5],
       [7, 8, 9]])

In [7]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [8]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.68099276, 0.05978104, 0.98346579, 0.75005459, 0.98240735])

In [13]:
np.random.randn(2,2)

array([[ 0.85518802, -1.22475893],
       [ 0.53892206,  0.81534365]])

In [14]:
np.random.randint(9)

4

In [15]:
ranarr = np.random.randint(0,20,6)

In [16]:
ranarr

array([ 7, 15, 13,  0,  2, 16])

In [17]:
ranarr.max()

16

In [18]:
ranarr.min()

0

In [19]:
ranarr.argmin()

3

In [21]:
ranarr.dtype

dtype('int64')

In [22]:
from numpy.random import randint

In [23]:
randint(1,10)

6

In [29]:
# index slicing
arr = np.arange(1,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[5]

6

In [31]:
arr[1:5]

array([2, 3, 4, 5])

In [32]:
arr_2d = np.array([[5,10,14],[20,23,4],[1,2,3]])

In [33]:
arr_2d

array([[ 5, 10, 14],
       [20, 23,  4],
       [ 1,  2,  3]])

In [35]:
arr_2d[2][2]

3

In [36]:
arr_2d[2,1]

2

In [38]:
arr_2d[:2,1:]

array([[10, 14],
       [23,  4]])

In [39]:
arr_2d[1:]

array([[20, 23,  4],
       [ 1,  2,  3]])

In [40]:
arr = np.arange(1,11)b

In [41]:
bool_arr = arr > 5

In [42]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [43]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [44]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [45]:
arr[arr<4]

array([1, 2, 3])

In [47]:
new_ar_2d = np.arange(50).reshape(5,10)
new_ar_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
new_ar_2d[1:3,2:5]

array([[12, 13, 14],
       [22, 23, 24]])

# Numpy operations

In [50]:
myarr = np.arange(0,11)

In [51]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
myarr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [53]:
myarr + myarr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
myarr- myarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
myarr / myarr

/tmp/ipykernel_3464/1628858692.py:1: RuntimeWarning: invalid value encountered in true_divide
  myarr / myarr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])